name: tphate_env
channels:
  - conda-forge
  - intel
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - appnope
  - argon2-cffi
  - asttokens
  - async_generator
  - attrs
  - backcall
  - binutils_impl_linux-64
  - binutils_linux-64
  - blas
  - bleach
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - certifi
  - cffi
  - cycler
  - cython
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - expat
  - fontconfig
  - freetype
  - gcc_impl_linux-64
  - gcc_linux-64
  - gettext
  - glib
  - gst-plugins-base
  - gstreamer
  - gxx_impl_linux-64
  - gxx_linux-64
  - h5py
  - hdf5
  - icu
  - impi_rt
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - intelpython
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab_pygments
  - jupyterlab_widgets
  - kernel-headers_linux-64
  - keyutils
  - krb5
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libcurl
  - libcxx
  - libcxxabi
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgfortran
  - libgfortran-ng
  - libgfortran4
  - libgomp
  - libgpuarray
  - libiconv
  - libnghttp2
  - libopenblas
  - libpng
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libuuid
  - libxcb
  - libxml2
  - libxslt
  - libzlib
  - llvm-openmp
  - lxml
  - mako
  - markupsafe
  - matplotlib-inline
  - mistune
  - mkl
  - more-itertools
  - mpi
  - mpi4py
  - mpich
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - nibabel
  - nilearn
  - nitime
  - notebook
  - numpy
  - numpy-base
  - openmp
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pip
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pybind11
  - pycparser
  - pydicom
  - pygments
  - pygpu
  - pyparsing
  - pyqt
  - pyrsistent
  - python
  - python-dateutil
  - python-fastjsonschema
  - python_abi
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - requests
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - sip
  - six
  - soupsieve
  - sqlite
  - stack_data
  - statsmodels
  - sysroot_linux-64
  - terminado
  - testpath
  - theano
  - threadpoolctl
  - tk
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zeromq
  - zlib
  - pip:
    - anyio
    - babel
    - brainiak
    - contextvars
    - dataclasses
    - demap
    - deprecated
    - future
    - graphtools
    - idna
    - immutables
    - importlib-resources
    - json5
    - jupyter-server
    - jupyterlab
    - jupyterlab-server
    - kiwisolver
    - llvmlite
    - matplotlib
    - nbclassic
    - numba
    - phate
    - pillow
    - pybind11-global
    - pygsp
    - pynndescent
    - s-gd2
    - scikit-learn
    - scprep
    - sniffio
    - tasklogger
    - tqdm
    - umap-learn
    - websocket-client
    - wrapt
    - zipp
